columns:
  job_id: int
  title: category
  location: category
  department: category
  salary_range: category
  company_profile: category
  description: category
  requirements: category
  benefits: category
  telecommuting: int
  has_company_logo: int
  has_questions: int
  employment_type: category
  required_experience: category
  required_education: category
  industry: category
  function: category
  fraudulent: int

numerical_columns:
  - job_id
  - telecommuting
  - has_company_logo
  - has_questions
  - fraudulent

categorical_columns:
  - title
  - location
  - department
  - salary_range
  - company_profile
  - description
  - requirements
  - benefits
  - employment_type
  - required_experience
  - required_education
  - industry
  - function

drop_columns: _id
